server:
  port: 8080

spring:
  application:
    name: finances

  datasource:
    url: ${DATABASE_URL} # variavel de ambiente do heroku, que providencia um banco padr√£o

  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: facildespesa@gmail.com
    password: D3spes@Fac1l
    test-connection: true


security:
  jwt:
    token:
      expire-in:  86400000
      secret-key: c2VjcmV0LWZpbmFuY2Vz